import {
  IMAGE_CHUNK_BYTES,
  MAX_IMAGE_DIMENSION,
  MAX_IMAGE_PIXELS,
  MAX_INLINE_IMAGE_BYTES,
  MAX_INLINE_IMAGE_TOTAL_BYTES,
  MAX_INLINE_IMAGE_TOTAL_PIXELS,
  MAX_INLINE_IMAGES,
} from "@markdown-review/contracts";

export {
  IMAGE_CHUNK_BYTES,
  MAX_IMAGE_DIMENSION,
  MAX_IMAGE_PIXELS,
  MAX_INLINE_IMAGE_BYTES,
  MAX_INLINE_IMAGE_TOTAL_BYTES,
  MAX_INLINE_IMAGE_TOTAL_PIXELS,
  MAX_INLINE_IMAGES,
};

export const MAX_MARKDOWN_BYTES = 2 * 1024 * 1024;
export const MAX_REVIEW_SESSIONS = 6;
export const MAX_REVIEW_SESSION_IMAGE_BYTES = 72 * 1024 * 1024;
export const REVIEW_SESSION_TTL_MS = 2 * 60 * 60 * 1000;
